FROM php:7.4-apache

WORKDIR /var/www/html
COPY . /var/www/html

RUN apt-get update

RUN apt-get install -y libpq-dev \
  && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
  && docker-php-ext-install pdo pdo_pgsql pgsql
