version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3601:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    links:
      - postgres

  postgres:
    image: postgres:latest
    container_name: des
    restart: always
    environment:
      POSTGRES_DB: desafio3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
